### ISSUE TITLE
[QA] Breed Pages

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#100]
https://main--petplace--hlxsites.hlx.live/article/breed/pembroke-welsh-corgi

- [x] Content in “Physical Characteristics” section is centered instead of lined up on the lefthand side.
- [x] Internal links and Facts section are still being implemented on AEM side.
- [x] Galaxy Fold: Other Breeds to Explore and References cut off.

![Image](https://user-images.githubusercontent.com/1235810/239645521-018c1669-2e13-423b-a39b-68682cb1624c.png)

- [x] large white space on the bottom of the "Care" carousel 
- [x] On opening the accordion, the bottom padding is missing from the paragraph copy and is touching the border

![Image](https://github.com/hlxsites/petplace/assets/1235810/38c15491-d345-4650-8d2c-a9a4e2c459a7)

- [x] The page is also using a different footer format in comparison with other blog articles

- [x] Cat image near footer

**Comment by travrob1** [comment]
Please give some extra clarification to the following points

- Internal links and Facts section are still being implemented on AEM side.
- Galaxy Fold: Other Breeds to Explore and References cut off.
-  The page is also using a different footer format in comparison with other blog articles
