### ISSUE TITLE
feat: add Google Ads

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#136]
PetPlace uses Google Publishers Tags (GPT) to place ads on the website.
The current implementation is obsolete:
```html
<script data-ad-client="ca-pub-6577733472295351" async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" data-checked-head="true"></script>
…
<ins class="adsbygoogle adsbygoogle-noablate" data-adsbygoogle-status="done" style="display: none !important;" data-ad-status="unfilled"></ins>
```

We need to be updated to the latest API versions and best-practices:

https://developers.google.com/publisher-tag/guides/ad-best-practices#use_single_request_architecture_correctly

Petplace is also re-designing how and where they will place ads, but we can already infer that we will need:
- An add placement in the sidebar for articles, like we already have on https://www.petplace.com/article/general/just-for-fun/valentines-from-your-pet/, probably even 2 slots on top of each-other. Those would be auto-decorated as part of the template.
- Inline adds inside articles that authors would need to be able to configure. So we are looking at an `Ads` block where the author can specify an identifier to be targeted by GPT.
- We will likely need a set of predefined block templates in the block library for the inline ads

**Comment by ramboz** [comment]
Petplace team is discussing internally how to migrate their existing GPT, and if things take longer than expected, we may have to temporarily fall back to the current implementation. We'll get updates on this closer to go-live, so for now we go with the latest APIs

**Comment by ramboz** [comment]
Here are the latest specs regarding sizing and placement:

[petplace_adplacementrs6.12.23.pdf](https://github.com/hlxsites/petplace/files/11739799/petplace_adplacementrs6.12.23.pdf)

**Comment by mfrisbey** [comment]
@ramboz, in addition to sizes, the google ad API requires an [ad unit path](https://developers.google.com/publisher-tag/guides/get-started#ad-unit-path). The path used in the examples I've seen is `/6355419/Travel/Europe/France`. Have they mentioned anything about those? If not I can follow up in slack
