### ISSUE TITLE
feat: implement puppy diary pages

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#195]
https://www.petplace.com/article/puppy-diaries/
https://www.petplace.com/article/puppy-diaries/can-we-get-a-puppy/
https://www.petplace.com/article/puppy-diaries/potty-training-puppy/
https://www.petplace.com/article/puppy-diaries/keeping-your-puppy-fit-dog-walking/
https://www.petplace.com/article/puppy-diaries/spaying-neutering-puppy/
https://www.petplace.com/article/puppy-diaries/eddie-loves-hudson/
https://www.petplace.com/article/puppy-diaries/moving-with-a-dog/

**Comment by ramboz** [comment]
We can likely use the generic template for the index one, using blade blocks.
The rest could be done with a template like the article page with the side column inverted if needed

**Comment by mfrisbey** [comment]
Based on comments from the pet place team, they seem to prefer the look of these pages in the existing article template. I don't think we'll need to change anything here, other than do a little cleanup on the index page.

**Comment by ramboz** [comment]
Agreed :)
