### ISSUE TITLE
After reviewing the pages above, there are several issues found (pls ignore it if these changes are done intentionally):

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#204]
After reviewing the pages above, there are several issues found (pls ignore it if these changes are done intentionally):
_The pages with checks ✔️have typical types of issues, but **many other pages** have the same issues._ 

1.  **Lack of Article page navigation** at the bottom (below is example):

Petplace (first pic) | Hlx.live (second pic)
-- | --
https://www.petplace.com/article/birds/general/what-to-do-if-your-bird-flies-the-coop/ | https://main--petplace--hlxsites.hlx.live/article/birds/general/what-to-do-if-your-bird-flies-the-coop

<img width="1312" alt="Screenshot 2023-06-29 at 10 19 21 PM" src="https://github.com/hlxsites/petplace/assets/105081458/3a205692-94cc-4258-a2e9-0a3f28d3eb8d">
<img width="1385" alt="Screenshot 2023-06-29 at 10 19 15 PM" src="https://github.com/hlxsites/petplace/assets/105081458/6d69a609-68cd-4161-80d3-bd013445fde2">

_Originally posted by @FentPams in https://github.com/hlxsites/petplace/issues/197#issuecomment-1614144669_

**Comment by ramboz** [comment]
Likely due to the index not having finished its job

**Comment by FentPams** [comment]
I'll check it after index finished.

**Comment by FentPams** [comment]
Handled in #203, same as #205
