### ISSUE TITLE
Article page navigation **miss** " **> next article**" -- The article navigation doesn't show "previous-thumbnail, and previous detail <1024px "(_display:none_). Some pages can work as expected, but most can't. Same for the screen >1024, the "next-thumbnail, next-details, next", don't show either.

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#205]
2. Article page navigation **miss** " **> next article**" -- The article navigation doesn't show "previous-thumbnail, and previous detail <1024px "(_display:none_). Some pages can work as expected, but most can't. Same for the screen >1024, the "next-thumbnail, next-details, next", don't show either.  

Petplace (1st. 2nd pic) | Hlx.live (3rd, 4th pic)
-- | --
https://www.petplace.com/article/dogs/breeds/dog-breeds/meet-the-vizsla/ | https://main--petplace--hlxsites.hlx.live/article/dogs/breeds/dog-breeds/meet-the-vizsla

-   \>1024 petplace
<img width="1272" alt="Screenshot 2023-06-29 at 10 26 26 PM" src="https://github.com/hlxsites/petplace/assets/105081458/e1511947-13e7-4adc-a1b5-b4acb36c099c">

-  <1024 petplace
<img width="421" alt="Screenshot 2023-06-29 at 10 26 34 PM" src="https://github.com/hlxsites/petplace/assets/105081458/2f87f87f-d569-4832-8eea-ff8e32749262">

-  \>1024 hlx
<img width="933" alt="Screenshot 2023-06-29 at 10 26 45 PM" src="https://github.com/hlxsites/petplace/assets/105081458/4f4fbce8-0047-4657-a3a3-aaddfab8893c">

-   <1024 hlx
<img width="251" alt="Screenshot 2023-06-29 at 10 26 39 PM" src="https://github.com/hlxsites/petplace/assets/105081458/4a75217d-044a-4c61-b6cf-5e877bda1fb7">

_Originally posted by @FentPams in https://github.com/hlxsites/petplace/issues/197#issuecomment-1614150685_

**Comment by ramboz** [comment]
Likely due to the index not having finished its job

**Comment by FentPams** [comment]
Handled in #203, same as #204
