### ISSUE TITLE
Bold text after initial headings got mis-formatted by importer

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#207]
#### 4.  Markup **text issue in doc**.

 For the html structure like this: 
```
<h2>
     <p> </p>  
     <p> </p>  
          …
</h2> 
```
<img width="495" alt="Screenshot 2023-06-29 at 10 53 49 PM" src="https://github.com/hlxsites/petplace/assets/105081458/f27408f4-b919-46f5-9e88-f0f82bf484db">
<img width="210" alt="Screenshot 2023-06-29 at 11 03 55 PM" src="https://github.com/hlxsites/petplace/assets/105081458/e705af95-7077-4be4-b50a-038ac5d97213">

- https://main--petplace--hlxsites.hlx.live/article/cats/pet-health/cleft-palate-in-cats  (I have manually adjusted its doc, but I guess there may be more pages like this)

- https://main--petplace--hlxsites.hlx.live/article/dogs/pet-health/malassezia-dermatitis-in-dogs (this one without fix yet)

_Originally posted by @FentPams in https://github.com/hlxsites/petplace/issues/197#issuecomment-1614810910_

**Comment by ramboz** [comment]
I've seen a few of these indeed. We can fix those we find, but since it's pretty easy to fix in the source document we can also defer a lot of this to post-golive.

**Comment by FentPams** [comment]
Has manually handled these we found already.
