### ISSUE TITLE
Mis-formatted heading

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#212]
#### 12. **Other text style** issue:

Petplace | Hlx.live
-- | --
https://www.petplace.com/article/cats/vet-qa-parent/vet-qa/why-does-my-cat-sleep-so-much/ | https://main--petplace--hlxsites.hlx.live/article/cats/vet-qa-parent/vet-qa/why-does-my-cat-sleep-so-much
<img width="870" alt="Screenshot 2023-06-30 at 12 00 57 AM" src="https://github.com/hlxsites/petplace/assets/105081458/debdee5b-0e06-435d-8679-faa112016527">

_Originally posted by @FentPams in https://github.com/hlxsites/petplace/issues/197#issuecomment-1614813750_

**Comment by ramboz** [comment]
I would suggest breaking the question to a new line here to fix this

**Comment by FentPams** [comment]
Manually handled.
