### ISSUE TITLE
Extra ** symbols in the content

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#214]
#### 13. **Extra symbols\*\***

Petplace | Hlx.live
-- | --
https://www.petplace.com/article/dogs/vet-qa-parent/vet-qa/what-is-gastric-lavage/ | https://main--petplace--hlxsites.hlx.live/article/dogs/vet-qa-parent/vet-qa/what-is-gastric-lavage
<img width="869" alt="Screenshot 2023-06-30 at 12 02 09 AM" src="https://github.com/hlxsites/petplace/assets/105081458/585045d5-2d8c-4be3-b280-7749f34c2f45">

_Originally posted by @FentPams in https://github.com/hlxsites/petplace/issues/197#issuecomment-1614814249_

**Comment by ramboz** [comment]
The importer blindly imports any bold/italic styles, but some WYSIWYG systems don't necessarily properly close those tags in the markup and hence when converting to markdown we end up with trailing ** or * symbols.

This unfortunately needs to be cleaned up manually. We can just remove those when we find them.

**Comment by FentPams** [comment]
Manually handled.
