### ISSUE TITLE
fix: sub-categories card content not show till refresh

### ISSUE THREAD

**Issue by FentPams** [hlxsites/petplace#231]
**Before refresh:**

Clicking the subcategories buttons, the cards don't display normally (see pic below). 

<img width="1459" alt="Screenshot 2023-07-07 at 12 31 49 PM" src="https://github.com/hlxsites/petplace/assets/105081458/e9215fde-b311-43e1-ada9-e0e8c984930a">

**Comment by FentPams** [comment]
Comment out the click event listener https://github.com/hlxsites/petplace/blob/main/templates/category-index/category-index.js#L164-L175 could fix this issue, but not sure if it's the right way to do it.  @ramboz  Would you mind taking a look? Thank you.

**Comment by ramboz** [comment]
Commenting out the click listener effectively disables the soft-navigation. I think we need to fix this differently. Will take a look and open a PR
